[alias]
xtask = "run --release --package xtask --"
day = "run --release --package xtask -- day"
2015 = "run --bin aoc_2015 --"
2021 = "run --bin aoc_2021 --"
2022 = "run --bin aoc_2022 --"
r2015 = "run --release --bin aoc_2015 --"
r2021 = "run --release --bin aoc_2021 --"
r2022 = "run --release --bin aoc_2022 --"
